// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0dQn5_jm90ZU_CrwY-_naDjMwmwqJEk',
    appId: '1:362183263895:web:f332f0ec836d57c16e8bd2',
    messagingSenderId: '362183263895',
    projectId: 'flavorway',
    authDomain: 'flavorway.firebaseapp.com',
    storageBucket: 'flavorway.firebasestorage.app',
    measurementId: 'G-5FBMR3M86R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92RX2ob1MPv5wG0vpFMxJieHJSh_xFz0',
    appId: '1:362183263895:android:539926a54362938f6e8bd2',
    messagingSenderId: '362183263895',
    projectId: 'flavorway',
    storageBucket: 'flavorway.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-zOO80FhkcGeL06swOUIvGULq7mvexg',
    appId: '1:362183263895:ios:0726c9d05d8d53d36e8bd2',
    messagingSenderId: '362183263895',
    projectId: 'flavorway',
    storageBucket: 'flavorway.firebasestorage.app',
    iosBundleId: 'ma.edigioweb.flavorway',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs-zOO80FhkcGeL06swOUIvGULq7mvexg',
    appId: '1:362183263895:ios:8ffdf7af70c270dc6e8bd2',
    messagingSenderId: '362183263895',
    projectId: 'flavorway',
    storageBucket: 'flavorway.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0dQn5_jm90ZU_CrwY-_naDjMwmwqJEk',
    appId: '1:362183263895:web:85117e2edd67300a6e8bd2',
    messagingSenderId: '362183263895',
    projectId: 'flavorway',
    authDomain: 'flavorway.firebaseapp.com',
    storageBucket: 'flavorway.firebasestorage.app',
    measurementId: 'G-Y5FCCRY2GF',
  );
}
